---
title: "Statistik 1"
author: "Daniel J. F. Gerber"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
---


# Vorwort {-}

Dieses Buch ist im Rahmen meiner Lehrtätigkeit an der FHNW entstanden und frei verfügbar.

```{r servebook, eval=FALSE, include=FALSE}
bookdown::serve_book()
```

```{r load_packages, include=FALSE}
# automatically create a bib database for R packages
library(tidyverse)
library(RColorBrewer)
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'jmv'
), 'packages.bib')
```

```{r foodef_plot_ball_bag, include=FALSE}
plot_ball_bag <- function(scores_bag, scores_hover, score_name, bag_color = "lightgrey", seed = NULL) {
  if (!is.null(seed)) set.seed(seed)
  
  n <- length(scores_bag)
  k <- length(scores_hover)
  # Generate scores and positions
  scores <- c(scores_bag, scores_hover)
  
  # Function to generate random positions within the bag
  random_position <- function(count, xmin, xmax, ymin, ymax) {
    data.frame(
      x = runif(count, xmin, xmax),
      y = runif(count, ymin, ymax)
    )
  }
  
  # Create dataframe for all balls
  df_bag <- random_position(n, 2.5, 7.5, 1.5, 5.5)
  df_hover <- data.frame(
    x = seq(3, 7, length.out = k),
    y = rep(7.5, k)
  )
  df_all <- rbind(
    cbind(df_bag, type = "bag", score = scores_bag),
    cbind(df_hover, type = "hover", score = scores_hover)
  )
  
  p <- ggplot() +
    geom_rect(aes(xmin = 2, xmax = 8, ymin = 1, ymax = 6), 
              fill = bag_color, color = "black", linewidth = 1) +
    geom_point(data = df_all, aes(x = x, y = y, color = score), size = 5) +
    scale_color_gradientn(colors = rev(brewer.pal(9, "RdYlGn")), 
                          name = score_name,
                          limits = c(min(scores), max(scores))) +
    annotate("text", x = 1.5, y = 3.5, label = "Population", angle = 90, hjust = 0.5) +
    annotate("text", x = 1.5, y = 7.5, label = "Stichprobe", angle = 90, hjust = 0.5) +
    # Add arrow
    annotate("segment", x = 5, xend = 5, y = 6.2, yend = 7,
             arrow = arrow(length = unit(0.3, "cm")), linewidth = 1) +
    # Adjust the plot
    coord_fixed(ratio = 1, xlim = c(0, 10), ylim = c(0, 10)) +
    theme_void() +
    theme(
      legend.position = "right",
      legend.title = element_text(angle = 0, vjust = 0.5),
      legend.box.margin = margin(0, 0, -50, -50)
    )
  
  return(p)
}
```