# Begriffsverzeichnis {-}

- [Ablehnungsbereich](#customdef-ablehnungsbereich)
- [Alternativhypothese](#customdef-alternativhypothese)
- [arithmetische Mittel](#customdef-arithmetisches-mittel)
- [Cohens $d$ f체r den Welch-Test](#customdef-welch-cohens-d)
- [Cohens $d$ f체r Zweistichproben-t-Test](#customdef-cohens-d)
- [einseitige Hypothese](#customdef-einseitige-hypothese)
- [Einstichproben-$t$-Test](#customdef-t-test)
- [Erwartungswert](#customdef-erwartungswert)
- [Freiheitsgrade](#customdef-freiheitsgrade)
- [Gegenl채ufig](#customdef-gegenlaeufig)
- [Glass $\Delta$](#customdef-glass-delta)
- [Gleichl채ufig](#customdef-gleichlaeufig)
- [Grundgesamtheit](#customdef-grundgesamtheit)
- [Hedges $g$](#customdef-hedges-g)
- [Hypothese](#customdef-hypothese)
- [Interquartilabstand](#customdef-iqr)
- [Intervalls](#customdef-interval)
- [intervallskaliert](#customdef-intervallskaliert)
- [Irrtumswahrscheinlichkeit](#customdef-erring-level)
- [Konfidenzintervall](#customdef-confidence-interval)
- [Korrelation](#customdef-korrelation)
- [Median](#customdef-median)
- [Modus](#customdef-modus)
- [nicht signifikant](#customdef-signifikanz)
- [Normalverteilung](#customdef-normalverteilung)
- [Nullhypothese](#customdef-nullhypothese)
- [partielle Korrelation](#customdef-partielle-korrelation)
- [Pearson](#customdef-pearson-korrelation)
- [Perzentil](#customdef-perzentil)
- [Population](#customdef-population)
- [Punktbiseriale Korrelation](#customdef-punktbiseriale-korrelation)
- [Signifikanzniveau](#customdef-signifikanzniveau)
- [Spannweite](#customdef-spannweite)
- [Spearman](#customdef-spearman-korrelation)
- [Standardabweichung](#customdef-std)
- [Stichprobe](#customdef-stichprobe)
- [Stichprobenziehung](#customdef-stichprobenziehung)
- [Streudiagramm](#customdef-streudiagramm)
- [Student-$t$-Verteilung](#customdef-student-verteilung)
- [Teststatistik](#customdef-teststatistik)
- [Vertrauenswahrscheinlichkeit](#customdef-confidence-level)
- [Welch-Test](#customdef-welch-test)
- [Zentraler Grenzwertsatz](#customdef-zentraler-grenzwertsatz)
- [Zufallsstichprobe](#customdef-zufallsstichprobe)
- [zweiseitige Hypothese](#customdef-zweiseitige-hypothese)
- [Zweistichproben-$t$-Test](#customdef-twosample-t-test)

# Literaturverzeichnis {-}
